#!/usr/bin/env perl
use v5.14;
use Getopt::Long;

use lib qw{ lib };
use Sleepr qw{ loop };

#
# Process CLI options
GetOptions(
    verbose => \my $verbose,
    help    => \my $help
);

if ( $help ) {
    say "Usage: $0 OPTIONS";
    exit 0;
}

loop {
    my ($cmd, @time) = @_;

    my ($sec, $min, $hour) = localtime;
    say "Checking for bedtime at $hour:$min:$sec..." if $verbose;

    if ( $hour >= $time[0] && $min >= $time[1] ) {
        system($cmd);
    }
}
